
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WageReport.java
 *
 * Created on Oct 15, 2011, 2:49:38 AM
 */
/**
 *
 * @author Tim
 */
public class WageForm extends javax.swing.JFrame {

    private double[][] earnings;
    private int index;
    
    /** Creates new form WageReport */
    public WageForm() {
        initComponents();
        earnings = new double[10][2];
        index = 0;
                   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tutorTime = new javax.swing.JTextField();
        paymentEarned = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputField = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        enterData = new javax.swing.JButton();
        runReport = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tutoring Waages Report");

        jLabel1.setText("Tutoring Time in Minutes");

        tutorTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorTimeActionPerformed(evt);
            }
        });

        paymentEarned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentEarnedActionPerformed(evt);
            }
        });

        outputField.setColumns(20);
        outputField.setRows(5);
        jScrollPane1.setViewportView(outputField);

        jLabel2.setText("Payment for session in dollars and cents");

        enterData.setText("Enter");
        enterData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterDataActionPerformed(evt);
            }
        });

        runReport.setText("Run Report");
        runReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runReportActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(runReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tutorTime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paymentEarned, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tutorTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentEarned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(enterData)
                        .addGap(45, 45, 45)
                        .addComponent(runReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void tutorTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorTimeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tutorTimeActionPerformed

private void runReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runReportActionPerformed
          
    //Displays in text area report title
    outputField.append("Report of your wages to Date:");
    outputField.append("\n"); //start a new line
    //add total time and earnings and display in text field
    double totalTime = 0, averageWage = 0;
    for(int i = 0; i < index; i++){
        totalTime += earnings[i][0];
        averageWage += earnings[i][1];
    }
    averageWage = averageWage/index;
    outputField.append("TotalTime: " + totalTime + "   AverageWage: " + averageWage);
    outputField.append("\n"); 
    
    if (averageWage < 7.75)
    {
    outputField.append("Your average wages per hour are below average");
    }
    else if (averageWage >= 7.75 && averageWage <= 7.75*2)
    {
    outputField.append("Your average wages per hour are then average");
    }
    else
    {
    outputField.append("Your average wages per hour are above average");
    }
    

}//GEN-LAST:event_runReportActionPerformed

private void paymentEarnedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentEarnedActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_paymentEarnedActionPerformed

private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
    System.exit(0);
}//GEN-LAST:event_quitButtonActionPerformed

private void enterDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterDataActionPerformed
// exception for minutes entered less than or equal to 0 and not greater than 240
    double tutorTime = 0;

    try {
        tutorTime = Double.parseDouble(
                this.tutorTime.getText());
        if (tutorTime <= 0 || tutorTime > 240) {
            throw new Exception();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Invalid input. Minutes can't be less than 0 or more than 240. Please try again",
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    double paymentEarned = 0;
    try {
        paymentEarned = Double.parseDouble(
                this.paymentEarned.getText());

        if (paymentEarned <= 0) {
            throw new Exception();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Invalid input. Earnings must be greater than zero. Please try again", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    // output from array displaying minutes and earnings. 
    if (index < 10) {
        earnings[index][0] = tutorTime;
        earnings[index][1] = paymentEarned;
        outputField.append("\n Minutes Earnings\n ***************************************");
        outputField.append("\n");
        outputField.append("Minutes: " + earnings[index][0] + "         ");
        outputField.append("Earnings: " + earnings[index][1] + "\n");
        index++;
        this.tutorTime.setText("");
        this.paymentEarned.setText("");
    } else {
        outputField.setText("You have exceeded the number of entries allowed (10).");
    }

// separates detail from report and lists all minutes and earnings in array

}//GEN-LAST:event_enterDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new WageForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputField;
    private javax.swing.JTextField paymentEarned;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton runReport;
    private javax.swing.JTextField tutorTime;
    // End of variables declaration//GEN-END:variables
}
